In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Ecommerce Purchases')

**Check the head of the DataFrame.**

In [3]:
df.head()

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82

**How many rows and columns are there?**

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Address           10000 non-null  str
 1   Lot               10000 non-null  str
 2   AM or PM          10000 non-null  str
 3   Browser Info      10000 non-null  str
 4   Company           10000 non-null  str
 5   Credit Card       10000 non-null  int64
 6   CC Exp Date       10000 non-null  str
 7   CC Security Code  10000 non-null  int64
 8   CC Provider       10000 non-null  str
 9   Email             10000 non-null  str
 10  Job               10000 non-null  str
 11  IP Address        10000 non-null  str
 12  Language          10000 non-null  str
 13  Purchase Price    10000 non-null  float64
dtypes: float64(1), int64(2), str(11)
memory usage: 1.1 MB

**What is the average Purchase Price?**

In [5]:
df['Purchase Price'].mean()

np.float64(50.347302)

**What were the highest and lowest purchase prices?**

In [6]:
df['Purchase Price'].max()

np.float64(99.99)

In [7]:
df['Purchase Price'].min()

np.float64(0.0)

In [8]:
df.describe()

        Credit Card  CC Security Code  Purchase Price
count  1.000000e+04      10000.000000    10000.000000
mean   2.341374e+15        907.217800       50.347302
std    2.256103e+15       1589.693035       29.015836
min    6.040186e+10          0.000000        0.000000
25%    3.056322e+13        280.000000       25.150000
50%    8.699942e+14        548.000000       50.505000
75%    4.492298e+15        816.000000       75.770000
max    6.012000e+15       9993.000000       99.990000

**How many people have English 'en' as their Language of choice on the website?**

In [19]:
df[df['Language'] == 'en']['Language'].count()
# df[df['Language'] == 'en']

np.int64(1098)

**How many people have the job title of "Lawyer" ?**

In [23]:
df['Job'].nunique()

623

In [25]:
df[df['Job'] == 'Lawyer']['Job'].count()

np.int64(30)

**How many people made the purchase during the AM and how many people made the purchase during PM ?**

In [28]:
df['Job'].value_counts()

Job
Interior and spatial designer    31
Lawyer                           30
Social researcher                28
Designer, jewellery              27
Purchasing manager               27
                                 ..
Special effects artist            7
Editor, film/video                6
Actuary                           6
Information systems manager       5
Investment analyst                5
Name: count, Length: 623, dtype: int64

**What are the 5 most common Job Titles?**

In [29]:
df['Job'].value_counts().head(5)

Job
Interior and spatial designer    31
Lawyer                           30
Social researcher                28
Designer, jewellery              27
Purchasing manager               27
Name: count, dtype: int64

**Someone made a purchase that came from Lot: "90 WT" , what was the Purchase Price for this transaction?**

In [30]:
df[df['Lot']=='90 WT']['Purchase Price']

513    75.1
Name: Purchase Price, dtype: float64

**What is the email of the person with the following Credit Card Number: 675957666125**

In [31]:
df[df["Credit Card"] == 675957666125]['Email']

2    amymiller@morales-harrison.com
Name: Email, dtype: str

**How many people have American Express as their Credit Card Provider *and* made a purchase above $95 ?**

In [32]:
df[(df['CC Provider']=='American Express') & (df['Purchase Price']>95)].count()

TypeError: Cannot perform 'rand_' with a dtyped [bool] array and scalar of type [bool]

**How many people have a credit card that expires in 2025?**

In [33]:
df.head(2)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73

In [36]:
def return_str(txt):
    return txt[3:]
df['CC Exp Date'].apply(return_str)
sum(df['CC Exp Date'].apply(lambda x: x[3:]) == '25')

df[df['CC Exp Date'].apply(lambda x: x[3:]) == '25']
# df['CC Exp Date']

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82
5,"7502 Powell Mission Apt. 768\nTravisland, VA 3...",21 XT,PM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_8_5...,Silva-Anderson,30246185196287,07/25,7169,Discover,ynguyen@gmail.com,Fish farm manager,55.96.152.147,ru,25.15
7,"260 Rachel Plains Suite 366\nCastroberg, WV 24...",96 pG,PM,Mozilla/5.0 (X11; Linux i686) AppleWebKit/5350...,Marshall-Collins,561252141909,06/25,256,VISA 13 digit,phillip48@parks.info,Event organiser,224.247.97.150,pt,44.25
13,"118 Melton Via Suite 681\nAlexanderbury, FL 32104",36 bu,PM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_8...,Keller PLC,4603635169938574,01/25,557,VISA 16 digit,caitlin57@yahoo.com,"Accountant, chartered public finance",84.212.92.11,it,8.93
15,"31730 Chelsea Crest\nBlakemouth, CT 90395-0620",41 Cj,PM,Opera/8.95.(Windows NT 5.0; en-US) Presto/2.9....,Garcia-Steele,180069437020404,04/25,404,Diners Club / Carte Blanche,amanda39@yahoo.com,Retail manager,53.176.235.33,el,71.78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9955,"66539 Potts Forge\nCartershire, AK 58271-5180",37 KB,AM,Mozilla/5.0 (compatible; MSIE 8.0; Windows CE;...,Russell PLC,4716539058450,02/25,2805,JCB 16 digit,matthewcontreras@bradshaw-skinner.com,Podiatrist,88.110.181.120,zh,84.09
9963,"3865 Davis Meadow Suite 915\nPort Stacieview, ...",11 fo,AM,Mozilla/5.0 (iPod; U; CPU iPhone OS 3_3 like M...,"Brown, Gentry and White",4295151255424068,07/25,764,JCB 15 digit,zjames@gmail.com,Surgeon,171.24.198.172,en,58.17
9993,"7555 Larson Locks Suite 229\nEllisburgh, MA 34...",72 jg,PM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_8...,Colon and Sons,30025560104631,10/25,629,Maestro,chelseawilliams@lopez.biz,"Designer, exhibition/display",177.46.82.128,el,65.61
9994,"6276 Rojas Hollow\nLake Louis, WY 56410-7837",93 Ex,PM,Opera/9.68.(X11; Linux x86_64; sl-SI) Presto/2...,Ritter-Smith,3112186784121077,01/25,1823,Maestro,iroberts@gmail.com,"Education officer, museum",242.44.112.18,zh,31.85
9996,"832 Curtis Dam Suite 785\nNorth Edwardburgh, T...",41 JY,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Hale, Collins and Wilson",210033169205009,07/25,207,JCB 16 digit,mary85@hotmail.com,Energy engineer,121.133.168.51,pt,25.63

**What are the top 5 most popular email providers/hosts (e.g. gmail.com, yahoo.com, etc...)**

In [37]:
df['Email'].apply(lambda x: x.split('@')[1]).value_counts().head(5)

Email
hotmail.com     1638
yahoo.com       1616
gmail.com       1605
smith.com         42
williams.com      37
Name: count, dtype: int64

# Great Job!