In [8]:
import pandas as pd

# Reading csv, excel, and json files in pandas

To read csv file in pandas, you can use the `read_csv` function.
To read excel file in pandas, you can use the `read_excel` function.
To read json file in pandas, you can use the `read_json` function.

Here are examples of how to use these functions:

```df = pd.read_csv('file.csv')``` 

```df = pd.read_excel('file.xlsx')```
 
```df = pd.read_json('file.json')```

In [9]:
df = pd.read_csv("sales_data_sample.csv", encoding="latin1")

df

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

# Creating a DataFrame from a dictionary and saving it as csv, excel, and json files

To create a DataFrame from a dictionary, you can use the `DataFrame` constructor from pandas. And we can save it as csv, excel, and json files using the `to_csv`, `to_excel`, and `to_json` methods respectively.
Here is an example of how to create a DataFrame from a dictionary and save it as different file formats:

```
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}```

```df = pd.DataFrame(data)

df.to_csv('file.csv', index=False)

df.to_excel('file.xlsx', index=False)

df.to_json('file.json', orient='records')```

In this example, we first create a dictionary with some sample data. Then we convert it into a DataFrame using ```pd.DataFrame()```. Finally, we save the DataFrame to a CSV file, an Excel file, and a JSON file using the respective methods. The ```index=False``` parameter is used to prevent pandas from writing row indices to the files.

In [10]:
# create dataframe and export it as csv, excel and json

data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}

custom_df = pd.DataFrame(data)

custom_df
# here we can see row index number by default

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [11]:
# removing the index while exporting

# to csv
custom_df.to_csv("custom_data.csv", index=False)

In [12]:
# to excel
custom_df.to_excel("custom_data.xlsx", index=False)

ModuleNotFoundError: No module named 'openpyxl'

In [ ]:
# to json
custom_df.to_json("custom_data.json", index=False)

In [ ]:
# head() --> by default it show first 5 rows. head(n) --> shows n number of rows

# df = pd.read_csv("/Users/istiakislam/projects/Learning-Data-Science/pandas/sales_data_sample.csv", encoding="latin1")


df.head()

In [ ]:
df.head(10)

In [ ]:
# tail(n) --> by default it shows last 5 rows and if provide n then it shows last n number of rows

df.tail(10)

# `info()`, `shape`, and `describe()` methods in pandas

Number of rows and columns in a DataFrame can be obtained using the `shape` attribute. The `shape` attribute returns a tuple where the first element is the number of rows and the second element is the number of columns.

And `info()` method provides a concise summary of the DataFrame, including the number of non-null entries, data types of each column, and memory usage.

The `describe()` method provides a statistical summary of the DataFrame, including count, mean, standard deviation, minimum, 25th percentile, median (50th percentile), 75th percentile, and maximum values for each numeric column.

Then `columns` attribute returns the column labels of the DataFrame as an Index object.

In [ ]:
df.info()

In [ ]:
df.shape # shows number of rows and column

In [ ]:

df.shape[0] # shows the number of rows only

In [ ]:

df.shape[1] # shows the number of columns only

In [ ]:
df.describe()

In [ ]:
# shows all the columns names
df.columns

select a

In [ ]:
# select a column --> this will return a series of dataframe
df["SALES"]

In [ ]:
# select multiple column --> this way inside [] will return as dataframe
df[["STATUS", "CITY"]]

In [ ]:
# simple row filtering

df[(df["STATUS"] == 'On Hold') & (df["QTR_ID"] > 3)]

In [ ]:
df[(df["QTR_ID"] > 3) | (df["STATUS"] == 'On Hold') ]

# Modifying and advanced filtering DataFrame in pandas

* Add a column to a DataFrame: You can add a new column to a DataFrame by assigning a value to a new column name. For example, `df['New_Column'] = value` will add a new column named 'New_Column' with the specified value. This value can be a constant, a list, or a result of an operation on existing columns. The new column will be added at the end of the DataFrame.
* Another way is inserting a column at a specific position using the `insert()` method. For example, `df.insert(loc=1, column='New_Column', value=value)` will insert a new column named 'New_Column' at index 1 (second position) with the specified value.

In [ ]:
df["DISCOUNT"] = df["PRICEEACH"] * 0.90

df

In [ ]:
df[["PRICEEACH", "DISCOUNT"]]

In [ ]:
# single column reorder using pop and insert

col = df.pop("DISCOUNT")

df.insert(3, "DISCOUNT", col)

df

In [ ]:
df.insert(3, "DISCOUNT_PERCENT", 10)
df

In [ ]:
# update a specific row value in a dataframe

df.loc[1, "PRICEEACH"] = 85.5

df

In [ ]:
# updating column value

df["PRICEEACH"] = df["PRICEEACH"] + 2

df

In [ ]:
# Removing a column
# inplace= True --> update the original dataframe, if False then it will return copy of dataframe without that column. Original dataframe will not affect.

# To remove multiple column use a list --> df.drop(columns=["DISCOUNT", "DISCOUNT_PERCENT"])

df.drop(columns="DISCOUNT", inplace=True)

df

# Handling missing values in pandas

To find missing values in a DataFrame, you can use the `isnull()` method, which returns a DataFrame of the same shape with boolean values indicating whether each element is missing (True) or not (False). To get the count of missing values in each column, you can chain the `sum()` method to `isnull()`, like this: `df.isnull().sum()`. This will return a Series with the count of missing values for each column in the DataFrame.

To handle missing values, you have several options:
1. **Drop missing values**: You can use the `dropna()` method to remove rows or columns that contain missing values. For example, `df.dropna()` will drop all rows that have at least one missing value, while `df.dropna(axis=1)` will drop all columns that have at least one missing value.

2. **Fill missing values**: You can use the `fillna()` method to replace missing values with a specified value or a method. For example, `df.fillna(0)` will replace all missing values with 0, while `df.fillna(method='ffill')` will forward-fill the missing values using the last valid observation.

3. **Interpolate missing values**: You can use the `interpolate()` method to estimate missing values based on the existing data. For example, `df.interpolate(method='linear')` will perform linear interpolation to fill in the missing values.

4. **Replace missing values with the mean, median, or mode**: You can calculate the mean, median, or mode of a column and use it to fill in the missing values. For example, `df['Column_Name'].fillna(df['Column_Name'].mean(), inplace=True)` will replace missing values in 'Column_Name' with the mean of that column.

5. **Use machine learning algorithms**: For more complex datasets, you can use machine learning algorithms to predict and fill in missing values based on the patterns in the data. This approach is more advanced and may require additional libraries such as scikit-learn.

In [ ]:
df.isnull().sum()

In [ ]:
df[["STATE"]]

In [ ]:
df["STATE"].value_counts()

In [ ]:
df["STATE"].mode()  # This return a series of data for most frequent occurring value

In [ ]:
df["STATE"].mode()[0]   # This will return the first value of most frequent value

In [ ]:
# drop missing data row
# drop missing data for state is null as this value is important for location analysis

df.dropna(subset=["STATE"], inplace=True)

df.isnull().sum()

In [ ]:
df["TERRITORY"]

In [ ]:
# fill the missing value with most frequent value as this is a categorical data


df["TERRITORY"]= df["TERRITORY"].fillna(df["TERRITORY"].mode()[0])

df["TERRITORY"]

In [ ]:

# then drop the entire column which is unnecessary

# ** once this code is run then second time it will occur an error as that column has been removed.
# df.drop(columns=["ADDRESSLINE2"], inplace=True)

In [ ]:
df.isnull().sum()

In [ ]:
df["POSTALCODE"]

In [ ]:
df["POSTALCODE"]= df["POSTALCODE"].fillna("UNKNOWN")

df["POSTALCODE"]

In [ ]:
df.isnull().sum()